# CMake generated Testfile for 
# Source directory: /Users/yuanzhixiang/workspace/source_code/mysql-5.5.62
# Build directory: /Users/yuanzhixiang/workspace/source_code/mysql-5.5.62
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs("zlib")
subdirs("extra/yassl")
subdirs("extra/yassl/taocrypt")
subdirs("cmd-line-utils/libedit")
subdirs("storage/archive")
subdirs("storage/blackhole")
subdirs("storage/csv")
subdirs("storage/example")
subdirs("storage/federated")
subdirs("storage/heap")
subdirs("storage/innobase")
subdirs("storage/myisam")
subdirs("storage/myisammrg")
subdirs("storage/perfschema")
subdirs("plugin/audit_null")
subdirs("plugin/auth")
subdirs("plugin/daemon_example")
subdirs("plugin/fulltext")
subdirs("plugin/semisync")
subdirs("include")
subdirs("dbug")
subdirs("strings")
subdirs("vio")
subdirs("regex")
subdirs("mysys")
subdirs("libmysql")
subdirs("unittest/mytap")
subdirs("unittest/mysys")
subdirs("unittest/my_decimal")
subdirs("extra")
subdirs("tests")
subdirs("client")
subdirs("sql")
subdirs("sql/share")
subdirs("libservices")
subdirs("mysql-test")
subdirs("mysql-test/lib/My/SafeProcess")
subdirs("support-files")
subdirs("scripts")
subdirs("sql-bench")
subdirs("man")
subdirs("packaging/rpm-oel")
subdirs("packaging/rpm-sles")
subdirs("packaging/rpm-docker")
subdirs("packaging/WiX")
subdirs("packaging/solaris")
